services:
  - type: web
    name: sosai-web
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sosai-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
    healthCheckPath: /
    autoDeploy: true
    plan: starter
    region: singapore
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

databases:
  - name: sosai-db
    databaseName: sosai
    user: sosai
    plan: free 