services:
  - type: web
    name: sosai03
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    plan: starter
    region: singapore
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 